service:
  name: shaders-website
plugins:
  - serverless-hooks-plugin
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

custom:
  hooks:
    before:package:createDeploymentArtifacts:
      - npm run build
  s3Sync:
    - bucketName: shaders-website
      localDir: dist
      acl: public-read